<?xml version="1.0"?>
<!--
Copyright (C) 2017, Raffaello Bonghi <raffaello@rnext.it>
All rights reserved

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright 
   notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.
3. Neither the name of the copyright holder nor the names of its 
   contributors may be used to endorse or promote products derived 
   from this software without specific prior written permission.
 
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND 
CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, 
BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS 
FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; 
OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, 
WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE 
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, 
EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-->
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="wheel">

  <xacro:macro name="wheel" params="type orientation conf name passive_wheel_type wheel_radius *visual_pose *wheel_pose *collision_shape">

  <!-- Front passive wheel all time type continous -->
  <link name="wheel_${type}_${conf}_Link">
    <inertial>
      <origin xyz="0 0 0.020143" rpy="0 0 0" />
      <mass value="0.0431" />
      <inertia ixx="0" ixy="0" ixz="0"
                       iyy="0" iyz="0"
                               izz="0" />
    </inertial>
    <visual>
      <xacro:insert_block name="visual_pose"/>
      <geometry>
        <mesh filename="${path_meshes}/track/${name}.STL" />
      </geometry>
      <material name="White-Alpha" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <xacro:insert_block name="collision_shape"/>
      </geometry>
    </collision>
  </link>
  <joint name="wheel_${type}_${conf}_joint" type="${passive_wheel_type}">
    <xacro:insert_block name="wheel_pose"/>
    <parent link="track_${type}_link" />
    <child link="wheel_${type}_${conf}_Link" />
    <axis xyz="0 0 ${-1 * orientation}" />

    <!-- Passive sprocket rotate automatically according to the status of the active one -->
    <xacro:if value="${passive_wheel_type == 'continuous'}">
      <mimic joint="${type}_joint" multiplier="${sprocket_radius/wheel_radius}" offset="0"/>
    </xacro:if>
  </joint>

  <gazebo reference="wheel_${type}_${conf}_Link">
    <material>Gazebo/GreyTransparent</material>
  </gazebo>

  </xacro:macro>
</robot>
